/**
 * Russian UI copy for screens and bootstrap states.
 * Keep user-facing strings here instead of scattering literals in screens.
 */

export const appCopy = {
	name: 'Дневник чтения',
	loading: 'Загрузка…',
	bootstrapErrorTitle: 'Не удалось открыть дневник',
	bootstrapErrorMessage:
		'Локальная база данных не инициализировалась. Попробуйте ещё раз.',
	retry: 'Повторить',
	comingSoonTitle: 'Скоро',
	comingSoonMessage: 'Эта функция появится в следующих обновлениях.',
	save: 'Сохранить',
	cancel: 'Отмена',
	edit: 'Изменить',
	delete: 'Удалить',
	archive: 'Архивировать',
	restore: 'Восстановить',
	authorUnknown: 'Автор не указан',
} as const

export const tabsCopy = {
	today: { title: 'Сегодня' },
	library: { title: 'Библиотека' },
	diary: { title: 'Дневник' },
	stats: { title: 'Статистика' },
	more: { title: 'Ещё' },
} as const

export const todayCopy = {
	title: 'Сегодня',
	emptyTitle: 'Сейчас ничего не читаете',
	emptyDescription:
		'Выберите книгу из библиотеки или добавьте новую — она появится здесь.',
	chooseFromLibrary: 'Выбрать из библиотеки',
	addBook: 'Добавить книгу',
	readingSection: 'Читаю сейчас',
	startReading: 'Начать чтение',
	continueSession: 'Продолжить чтение',
	activeSessionBanner: 'Незавершённая сессия',
	setExact: 'Указать',
	progressUpdated: 'Прогресс обновлён',
	undo: 'Отменить',
	plus1: '+1',
	plus10: '+10',
	plus25: '+25',
	plus1pct: '+1%',
	plus5pct: '+5%',
	plus10pct: '+10%',
	plus10min: '+10 мин',
	plus30min: '+30 мин',
	plus60min: '+60 мин',
	setGoal: 'Поставить цель',
	todayGoals: 'Цели на сегодня',
} as const

export const sessionCopy = {
	title: 'Читаем',
	finish: 'Завершить',
	cancelSession: 'Отменить сессию',
	cancelConfirmTitle: 'Отменить сессию?',
	cancelConfirmMessage:
		'Сессия будет удалена. Прогресс книги не изменится.',
	cancelConfirmAction: 'Удалить сессию',
	startedFromPages: (page: number) => `Начали со стр. ${page}`,
	startedFromPercent: (percent: number) =>
		`Начали с ${Math.round(percent)}%`,
	startedFromTime: (label: string) => `Начали с ${label}`,
	longSessionWarning:
		'Сессия длится уже более 12 ч. Проверьте, не забыли ли вы её завершить.',
	conflictTitle: 'Уже идёт чтение',
	conflictMessage: (title: string) =>
		`У вас уже идёт чтение «${title}».`,
	returnToSession: 'Вернуться к сессии',
	finishExisting: 'Завершить её',
	finishTitle: 'Итог сессии',
	save: 'Сохранить',
	discard: 'Не сохранять',
	was: 'Было',
	now: 'Сейчас',
	durationLabel: (label: string) => `${label} чтения`,
	historyTitle: 'История чтения',
	historyEmpty: 'Сессий пока нет',
	historyAll: 'Вся история',
	deleteSession: 'Удалить запись',
	deleteSessionHint:
		'Удалит только запись сессии. Текущий прогресс книги не пересчитается.',
	completionTitle: 'Книга закончена',
	completionMessage: 'Отметить как прочитанную?',
	completionLater: 'Позже',
	completionDone: 'Прочитано',
	rateOptional: 'Оценить книгу',
	markFinished: 'Отметить прочитанной',
	continueReading: 'Продолжить чтение',
	returnToBook: 'Вернуться к книге',
	reopenReading: 'Читать снова',
	exactTitle: 'Указать прогресс',
	pageLabel: 'Текущая страница',
	percentLabel: 'Процент',
	hoursLabel: 'Часы',
	minutesLabel: 'Минуты',
} as const

export const libraryCopy = {
	title: 'Библиотека',
	emptyTitle: 'Ваша библиотека пока пуста',
	emptyDescription: 'Добавьте первую книгу — это займёт меньше минуты.',
	addBook: 'Добавить книгу',
	addBookShort: '+ Добавить',
	searchPlaceholder: 'Поиск по книгам и авторам',
	filterEmpty: (statusLabel: string) =>
		`В разделе «${statusLabel}» пока нет книг.`,
	sort: 'Сортировка',
	shelves: 'Полки',
	countsReading: 'Читаю',
	countsWant: 'Хочу',
	countsFinished: 'Прочитано',
} as const

export const searchCopy = {
	hubTitle: 'Добавить книгу',
	hubSearchTitle: 'Найти книгу',
	hubSearchHint: 'Быстрый поиск по каталогу — название, автор или ISBN',
	hubManualTitle: 'Добавить вручную',
	hubManualHint: 'Работает без интернета',
	hubScanTitle: 'Сканировать штрихкод',
	hubScanHint: 'ISBN с обложки книги',
	title: 'Поиск книг',
	placeholder: 'Название, автор или ISBN',
	initialTitle: 'Найдите книгу по названию, автору или ISBN.',
	initialHint: 'Можно также отсканировать штрихкод или добавить книгу вручную.',
	loading: 'Ищем книги…',
	emptyTitle: 'Ничего не нашли',
	emptyHint: 'Попробуйте изменить запрос или добавьте книгу вручную.',
	changeQuery: 'Изменить запрос',
	manualAdd: 'Добавить вручную',
	networkErrorTitle: 'Не удалось выполнить поиск',
	networkErrorHint: 'Проверьте подключение к интернету.',
	retry: 'Повторить',
	add: 'Добавить',
	searchAction: 'Найти',
	previewTitle: 'Добавить в библиотеку',
	previewEdit: 'Изменить данные',
	previewSubmit: 'Добавить в библиотеку',
	addedToast: 'Книга добавлена в библиотеку',
	duplicateTitle: 'Эта книга уже есть в библиотеке',
	duplicateOpen: 'Открыть',
	duplicateAddEdition: 'Добавить другое издание',
	attribution: 'Метаданные: Open Library',
} as const

export const scanCopy = {
	title: 'Сканер ISBN',
	permissionExplain:
		'Камера нужна только для сканирования штрихкода книги.',
	permissionAllow: 'Разрешить камеру',
	permissionDeniedTitle: 'Разрешение на камеру не предоставлено',
	permissionDeniedHint: 'Можно ввести ISBN вручную или повторить запрос.',
	tryAgain: 'Попробовать снова',
	enterIsbn: 'Ввести ISBN вручную',
	lookingUp: 'Ищем книгу по ISBN…',
	notBookland: 'Этот штрихкод не похож на ISBN книги.',
	notFound: 'Книга с таким ISBN не найдена',
	manualFallback: 'Добавить вручную',
} as const

export const addBookCopy = {
	title: 'Добавить книгу',
	editTitle: 'Изменить книгу',
	titleLabel: 'Название',
	titlePlaceholder: 'Название книги',
	authorLabel: 'Автор',
	authorPlaceholder: 'Имя автора (необязательно)',
	moreDetails: 'Дополнительные сведения',
	subtitleLabel: 'Подзаголовок',
	isbn10Label: 'ISBN-10',
	isbn13Label: 'ISBN-13',
	publisherLabel: 'Издательство',
	yearLabel: 'Год издания',
	pageCountLabel: 'Страниц в книге',
	descriptionLabel: 'Описание',
	formatLabel: 'Формат',
	statusLabel: 'Статус',
	progressModeLabel: 'Как отмечать прогресс',
	currentPageLabel: 'Текущая страница',
	totalPagesLabel: 'Всего страниц',
	percentLabel: 'Прогресс, %',
	audioPositionLabel: 'Текущая позиция',
	audioDurationLabel: 'Длительность',
	hoursLabel: 'ч',
	minutesLabel: 'мин',
	ratingLabel: 'Оценка',
	reviewLabel: 'Мой отзыв',
	reviewPlaceholder: 'Личные впечатления (необязательно)',
	finishedWhenLabel: 'Когда прочитали?',
	finishedToday: 'Сегодня',
	finishedThisYear: 'В этом году',
	finishedEarlier: 'Раньше',
	finishedPickDate: 'Указать дату',
	finishedYearLabel: 'Год прочтения',
	finishedDateLabel: 'Дата прочтения',
	shelvesLabel: 'Полки',
	submitAdd: 'Добавить',
	submitSave: 'Сохранить',
	duplicateTitle: 'Похожая книга уже есть в библиотеке',
	duplicateOpen: 'Открыть существующую',
	duplicateAddAnyway: 'Всё равно добавить',
	useBookPageCount: 'Использовать число страниц из книги',
} as const

export const bookDetailsCopy = {
	progress: 'Прогресс',
	metadata: 'Сведения',
	personal: 'Мои данные',
	shelves: 'Полки',
	archiveTitle: 'Архивировать книгу?',
	archiveMessage:
		'Книга исчезнет из активной библиотеки, но история чтения сохранится.',
	archiveConfirm: 'Архивировать',
	finished: 'Прочитано',
	noProgress: 'Прогресс не указан',
	noRating: 'Без оценки',
	history: 'История чтения',
	notes: 'Цитаты и заметки',
} as const

export const archiveCopy = {
	title: 'Архив книг',
	emptyTitle: 'Архив пуст',
	emptyDescription: 'Архивированные книги появятся здесь.',
	restored: 'Книга возвращена в библиотеку',
} as const

export const shelvesCopy = {
	title: 'Полки',
	emptyTitle: 'Полок пока нет',
	emptyDescription: 'Создайте полку — например «Любимые» или «Классика».',
	create: 'Создать полку',
	rename: 'Переименовать',
	archive: 'Архивировать полку',
	nameLabel: 'Название полки',
	namePlaceholder: 'Например, Любимые',
	archiveConfirmTitle: 'Архивировать полку?',
	archiveConfirmMessage:
		'Книги останутся в библиотеке, связь с полкой будет снята из активных списков.',
} as const

export const diaryCopy = {
	title: 'Дневник',
	emptyTitle: 'Здесь появится история вашего чтения',
	emptyDescription: 'Начните читать или сохраните первую цитату.',
	goToBooks: 'Перейти к книгам',
	filterAll: 'Все',
	filterSessions: 'Сессии',
	filterQuotes: 'Цитаты',
	filterThoughts: 'Мысли',
	filterNotes: 'Заметки',
	allBooks: 'Все книги',
	searchPlaceholder: 'Поиск по цитатам и заметкам',
	newNote: 'Новая запись',
	editNote: 'Изменить запись',
	noteDetails: 'Запись',
	addNote: 'Добавить запись',
	addQuote: '+ Цитата',
	addThought: '+ Мысль',
	addNoteShort: '+ Заметка',
	addNoteDuringSession: 'Добавить запись',
	addNoteAfterSession: 'Добавить заметку',
	typeQuote: 'Цитата',
	typeThought: 'Мысль',
	typeNote: 'Заметка',
	placeholderQuote: 'Введите текст цитаты',
	placeholderThought: 'Запишите свою мысль',
	placeholderNote: 'Добавьте заметку',
	locationSection: 'Место в книге',
	pageLabel: 'Страница',
	percentLabel: 'Процент',
	positionLabel: 'Позиция',
	hoursLabel: 'Часы',
	minutesLabel: 'Минуты',
	linkedSession: 'Связано с текущей сессией',
	linkedSessionPast: 'Связано с сессией чтения',
	textRequired: 'Введите текст записи',
	textTooLong: 'Текст слишком длинный',
	invalidType: 'Некорректный тип записи',
	invalidPage: 'Страница должна быть целым числом от 0',
	pageExceedsTotal: 'Страница не может быть больше общего числа',
	invalidPercent: 'Процент должен быть от 0 до 100',
	invalidAudio: 'Позиция не может быть отрицательной',
	audioExceeds: 'Позиция не может превышать длительность',
	deleteTitle: 'Удалить запись?',
	deleteMessage: 'Запись будет удалена без возможности восстановления.',
	deleteConfirm: 'Удалить',
	copy: 'Копировать',
	copied: 'Скопировано',
	share: 'Поделиться',
	dirtyTitle: 'Сохранить изменения?',
	dirtyDiscard: 'Не сохранять',
	dirtyKeep: 'Продолжить редактирование',
	dirtySave: 'Сохранить',
	notesSection: 'Цитаты и заметки',
	allNotes: 'Все записи',
	notesEmpty: 'Пока нет записей',
	counts: (quotes: number, thoughts: number, notes: number) =>
		`${quotes} цитат · ${thoughts} мыслей · ${notes} заметок`,
	loadMore: 'Ещё',
} as const

export const statsCopy = {
	title: 'Статистика',
	emptyTitle: 'Статистика появится после первых записей о чтении.',
	emptyDescription:
		'Отмечайте чтение сессиями или быстрым прогрессом — сводка появится здесь.',
	periodTitle: 'Период',
	periodD7: '7 дней',
	periodD30: '30 дней',
	periodD90: '90 дней',
	periodYearStats: 'Год',
	periodAll: 'Всё',
	summaryTitle: 'Сводка',
	summaryBooks: 'Книги',
	summaryPages: 'Страницы',
	summaryTime: 'Время',
	summaryDays: 'Дни чтения',
	noTimeData: 'Нет данных',
	percentInsight: (n: number) => `+${Math.round(n)}% прогресса`,
	chartTitle: 'Динамика чтения',
	chartMetricTime: 'Время',
	chartMetricPages: 'Страницы',
	chartEmpty: 'Пока недостаточно данных для графика.',
	booksByMonthTitle: 'Книги по месяцам',
	yearPrecisionHint: (n: number) =>
		`Ещё ${n} ${n === 1 ? 'книга имеет' : n < 5 ? 'книги имеют' : 'книг имеют'} только год прочтения.`,
	unknownPrecisionHint: (n: number) =>
		`${n} ${n === 1 ? 'книга без даты' : n < 5 ? 'книги без даты' : 'книг без даты'} прочтения.`,
	formatsTitle: 'Форматы',
	formatPaper: 'Бумажные',
	formatEbook: 'Электронные',
	formatAudio: 'Аудио',
	libraryNowTitle: 'Библиотека сейчас',
	ratingsTitle: 'Оценки',
	ratingAverage: (v: string) => `Средняя оценка ${v}`,
	ratingCoverage: (rated: number, total: number) =>
		`Оценено ${rated} из ${total} книг`,
	topBooksTitle: 'Больше всего читали',
	topAuthorsTitle: 'Чаще всего читали',
	authorBooks: (n: number) =>
		`${n} ${n === 1 ? 'книга' : n < 5 ? 'книги' : 'книг'}`,
	mostActiveDayTitle: 'Самый активный день',
	averagesTitle: 'В среднем',
	avgPerActiveDayTime: 'за день чтения',
	avgPerActiveDayPages: 'страниц за день чтения',
	sessionsTitle: 'Сессии',
	sessionsCount: 'Сессий',
	sessionsAvg: 'Средняя',
	sessionsMax: 'Самая длинная',
	notesTitle: 'Записи дневника',
	notesQuote: 'Цитат',
	notesThought: 'Мыслей',
	notesNote: 'Заметок',
	paceTitle: 'Темп чтения',
	pacePages: (n: number) =>
		`За последние 30 дней: ${n} стр./активный день`,
	calendarCompactTitle: 'Календарь',
	streakTitle: 'Серия дней',
	streakEmpty: 'Серия начнётся после первого дня чтения.',
	streakCurrent: (n: number) => `${n} дн. подряд`,
	streakBest: (n: number) => `Лучшая серия: ${n}`,
	streakContinue: 'Сегодня ещё можно продолжить серию.',
	calendarTitle: 'Календарь',
	goalsTitle: 'Цели',
	goalsEmpty: 'Поставьте цель, если хотите читать регулярнее.',
	createGoal: 'Создать цель',
	addGoal: '+ Цель',
	editGoal: 'Изменить цель',
	archiveGoal: 'Архивировать',
	archiveGoalConfirm: 'Архивировать цель?',
	goalType: 'Тип',
	goalPeriod: 'Период',
	goalTarget: 'Значение',
	goalPages: 'Страницы',
	goalMinutes: 'Минуты',
	goalBooks: 'Книги',
	periodDay: 'День',
	periodWeek: 'Неделя',
	periodMonth: 'Месяц',
	periodYear: 'Год',
	remainingPages: (n: number) => `До цели осталось ${n} страниц.`,
	remainingMinutes: (n: number) => `До цели осталось ${n} минут.`,
	remainingBooks: (n: number) => `До цели осталось ${n} книг.`,
	completed: 'Выполнено',
	duplicateGoalTitle: 'Похожая цель уже есть',
	duplicateGoalMessage: 'Создать ещё одну такую же?',
	duplicateCreate: 'Создать',
	daySessions: (n: number) =>
		n === 1 ? '1 сессия' : `${n} сессии`,
	dayMinutes: (n: number) => `${n} мин`,
	dayPages: (n: number) => `${n} стр.`,
	dayPercent: (n: number) => `+${Math.round(n)}%`,
	dayAudio: (label: string) => `+${label} позиции`,
	dayNotes: (n: number) => `${n} записей`,
	dayEmpty: 'В этот день чтения не было.',
	weekdays: ['пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс'] as const,
	presetPages: '20 страниц в день',
	presetMinutes: '30 минут в день',
	presetBooks: '12 книг в год',
	placeholderBooks: 'Книги',
	placeholderPages: 'Страницы',
	placeholderTime: 'Время',
	placeholderDays: 'Дни чтения',
	placeholderValue: '—',
	yearInBooksEntry: 'Мой год в книгах',
	yearInBooksHint: 'Красивый итог выбранного года',
} as const

export const yearInBooksCopy = {
	back: 'Назад',
	brand: 'Дневник чтения',
	coverTitle: (year: number) => `Мой ${year} год в книгах`,
	coverSubtitle: 'Год, который я прочитал',
	emptyTitle: (year: number) => `В ${year} году пока нет данных о чтении.`,
	emptyDescription:
		'Когда появятся сессии, прогресс или прочитанные книги — здесь соберётся итог года.',
	numbersTitle: 'Главные числа',
	yearPrecisionHint: (n: number) =>
		`Ещё ${n} ${n === 1 ? 'книга с известным только годом' : n < 5 ? 'книги с известным только годом' : 'книг с известным только годом'}.`,
	paceTitle: 'Ритм чтения',
	avgPerActiveDay: 'в среднем за активный день',
	avgPagesPerDay: 'страниц за активный день',
	longestSession: 'Самая длинная сессия',
	sessionsTotal: (n: number) => `Всего сессий: ${n}`,
	monthTitle: 'Лучший месяц',
	monthByTime: 'Больше всего времени читали',
	monthByPages: 'Больше всего страниц',
	monthSecondary: (month: string, pages: string) =>
		`Больше всего страниц — в ${month.toLowerCase()}: ${pages}`,
	topBooksTitle: 'Больше всего читали',
	topBooksByTime: 'По времени сессий',
	topBooksByPages: 'По прочитанным страницам',
	insightsTitle: 'Любимое',
	topAuthor: 'Чаще всего читали',
	favoriteFormat: 'Любимый формат',
	avgRating: 'Средняя оценка',
	highestRated: 'Самая высокая оценка',
	longestBook: 'Самая длинная книга',
	activityTitle: 'Активность',
	bestStreak: (n: number) => `Лучшая серия в этом году: ${n} дн.`,
	notesTitle: 'Дневник',
	quotes: (n: number) => `${n} ${n === 1 ? 'цитата' : n < 5 ? 'цитаты' : 'цитат'}`,
	thoughts: (n: number) => `${n} ${n === 1 ? 'мысль' : n < 5 ? 'мысли' : 'мыслей'}`,
	notes: (n: number) => `${n} ${n === 1 ? 'заметка' : n < 5 ? 'заметки' : 'заметок'}`,
	quoteSample: 'Одна из ваших цитат года',
	shareTitle: 'Итог года',
	share: 'Поделиться',
	sharing: 'Готовим…',
} as const

export const moreCopy = {
	title: 'Ещё',
	subtitle: 'Настройки и сведения о приложении',
	backup: 'Резервная копия',
	backupHint: 'Создать или восстановить полную копию данных',
	exportData: 'Экспорт данных',
	exportDataHint: 'CSV библиотеки и PDF-отчёт',
	reminders: 'Напоминания',
	remindersHint: 'Настройка ежедневных напоминаний появится позже',
	archive: 'Архив книг',
	archiveHint: 'Восстановление архивированных книг',
	shelves: 'Полки',
	shelvesHint: 'Коллекции вроде «Любимые» или «Классика»',
	about: 'О приложении',
	aboutHint: 'Дневник чтения · версия 1.0.0',
	aboutBody:
		'Личный offline-first дневник чтения. Основные действия доступны без регистрации и без интернета.',
} as const

export const backupCopy = {
	title: 'Резервная копия',
	subtitle:
		'Копия включает библиотеку, прогресс, историю чтения, цитаты, заметки, цели и настройки.',
	privacy:
		'Файлы создаются на устройстве и никуда не отправляются автоматически.',
	create: 'Создать копию',
	restoreFromFile: 'Восстановить из файла',
	creating: 'Создаём резервную копию…',
	restoring: 'Восстанавливаем данные…',
	createdTitle: 'Резервная копия создана',
	createdBody: (books: number, sessions: number, notes: number) =>
		`${books} книг · ${sessions} сессий · ${notes} записей`,
	share: 'Поделиться',
	done: 'Готово',
	cancel: 'Отмена',
	restore: 'Восстановить',
	makeSafetyBackup: 'Сначала сохранить текущие',
	restoreConfirmTitle: 'Восстановить резервную копию?',
	restoreConfirmBody:
		'Текущие данные приложения будут заменены данными из выбранной копии.',
	restoreSuccessTitle: 'Данные успешно восстановлены',
	restoreSuccessBody: 'Библиотека и история чтения загружены из копии.',
	errorTitle: 'Ошибка',
	backupFailed: 'Не удалось создать резервную копию.',
	restoreFailed:
		'Не удалось восстановить резервную копию. Файл повреждён или имеет неподдерживаемый формат.',
} as const

export const exportCopy = {
	title: 'Экспорт данных',
	subtitle: 'Читаемые файлы для вас — не полная резервная копия.',
	privacy:
		'Файлы создаются на устройстве и никуда не отправляются автоматически.',
	csvTitle: 'Библиотека CSV',
	csvHint: 'Таблица для Excel и других программ.',
	csvAction: 'Экспортировать CSV',
	pdfTitle: 'Библиотека PDF',
	pdfHint: 'Читаемый отчёт по книгам.',
	pdfAction: 'Создать PDF',
	filterAll: 'Вся библиотека',
	filterFinished: 'Прочитанные',
	filterReading: 'Читаю',
	filterWant: 'Хочу прочитать',
	creatingCsv: 'Создаём CSV…',
	creatingPdf: 'Создаём PDF…',
	csvReady: 'Файл CSV создан',
	pdfReady: 'PDF создан',
	errorTitle: 'Ошибка',
	csvFailed: 'Не удалось создать CSV.',
	pdfFailed: 'Не удалось создать PDF.',
} as const

export const validationCopy = {
	titleRequired: 'Укажите название книги',
	invalidYear: 'Год издания должен быть от 1000 до текущего + 1',
	invalidIsbn10: 'Проверьте ISBN-10',
	invalidIsbn13: 'Проверьте ISBN-13',
	invalidPage: 'Страница должна быть целым числом от 0',
	invalidTotalPages: 'Всего страниц должно быть больше 0',
	pageExceedsTotal: 'Текущая страница не может быть больше общего числа',
	invalidPercent: 'Процент должен быть от 0 до 100',
	invalidAudio: 'Время не может быть отрицательным',
	audioPositionExceeds: 'Позиция не может превышать длительность',
	invalidRating: 'Оценка от 0 до 5 с шагом 0.5',
	invalidStatus: 'Некорректный статус',
	invalidFormat: 'Некорректный формат',
	invalidProgressMode: 'Некорректный режим прогресса',
	invalidFinishedDate: 'Укажите корректную дату прочтения',
	invalidFinishedYear: 'Укажите корректный год прочтения',
	shelfNameRequired: 'Укажите название полки',
} as const
